services:
  postgres:
    image: postgres:17.11
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: docker
      POSTGRES_PASSWORD: docker
      POSTGRES_DB: financial_manager
    volumes:
      - financial_manager_postgres_data:/var/lib/postgresql/data

volumes:
  financial_manager_postgres_data: